version: '3.8'

services:
  # Tvoja Go aplikacija
  app:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://nemanja:mojasifra@db:5432/iot_db?sslmode=disable
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=nemanja
      - DB_PASSWORD=mojasifra
      - DB_NAME=iot_db

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: nemanja
      POSTGRES_PASSWORD: mojasifra
      POSTGRES_DB: iot_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config

volumes:
  postgres_data: